### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by nmeirik** [transfer-framework/bundle#4]
When running `composer require transfer/bundle` in my project, I get the following error:

```
[InvalidArgumentException]                                                                 
  Could not find package transfer/bundle at any version for your minimum-stability (stable)  
  . Check the package spelling or your minimum-stability
```

I assume that this is due to the fact that the package does not appear to be registered at Packagist.org.

**Comment by valisj** [comment]
Transfer bundle wasn't released with a stable enough version at that moment. 

Now that a stable release is published, you should be able to download and install `transfer/bundle` now.

**Comment by valisj** [comment]
@nmeirik Installation on a fresh Symfony distribution works fine.
